import dash
from dash import dcc, html, dash_table, callback, Input, Output
import dash_bootstrap_components as dbc
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
import pathlib
import sys
import pytz
import calendar

# PATH SETUP
ROOT_DIR = pathlib.Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT_DIR))

from src.core import engine_forensics as forensics
from src.utils.date_profiles import DATE_PROFILES

TZ_UTC = pytz.UTC
TZ_PST = pytz.timezone('US/Pacific')

# ==============================================================================
# 1. LAYOUT
# ==============================================================================
def render():
    # ⚡ NUCLEAR STYLE: HIGH CONTRAST (Black Text / White Background)
    INPUT_STYLE = {
        'color': '#000000', 
        'backgroundColor': '#ffffff', 
        'fontFamily': 'monospace',
        'border': '1px solid #ccc'
    }

    return dbc.Container([
        
        # --- TITLE ROW ---
        dbc.Row([
            dbc.Col([
                html.H2("STATISTICAL METRICS", className="fw-bold text-white mb-0"),
                html.P("CAPITAL ALLOCATION | CALL vs PUT BIAS | BURN RATE", className="text-muted small fw-bold mb-0")
            ], width=8),
            
            dbc.Col([
                html.Div("ANALYTICS ENGINE: ACTIVE", className="text-end text-success font-monospace fw-bold"),
                html.Div("COMPANION: TRADE AUDIT", className="text-end text-info font-monospace small")
            ], width=4, className="align-self-center")
        ], className="mb-4 py-3 border-bottom border-secondary"),

        # --- CONTROLS ---
        dbc.Row([
            dbc.Col([
                html.Label("LEDGER SOURCE", className="small text-muted fw-bold"),
                dbc.Select(
                    id='stats-source',
                    options=[{'label': 'GIL LEDGER (Robinhood)', 'value': 'rh'}, {'label': 'SIMULATION', 'value': 'gen'}],
                    value='rh', 
                    style=INPUT_STYLE,
                    className="mb-3 text-dark"
                )
            ], width=6),
            dbc.Col([
                html.Label("LOOKBACK PROFILE", className="small text-muted fw-bold"),
                dbc.Select(
                    id='stats-profile',
                    options=[{'label': k, 'value': k} for k in DATE_PROFILES.keys()],
                    value='Year To Date', 
                    style=INPUT_STYLE,
                    className="mb-3 text-dark"
                )
            ], width=6)
        ]),

        # --- KPI ROW (Generated by Callback) ---
        dbc.Row(id='stats-kpi-row', className="mb-4"),

        # --- ROW 1: THE SPLIT (Call vs Put) ---
        dbc.Row([
            dbc.Col(dbc.Card([
                dbc.CardHeader("DIRECTIONAL BIAS (75/25 SPLIT)", className="fw-bold font-monospace small"), 
                dbc.CardBody(dcc.Graph(id='stats-chart-split', style={'height': '300px'}, config={'displayModeBar': False}))
            ], className="shadow-sm border-secondary h-100"), width=6),
            
            dbc.Col(dbc.Card([
                dbc.CardHeader("WIN RATE BY INSTRUMENT", className="fw-bold font-monospace small"), 
                dbc.CardBody(dcc.Graph(id='stats-chart-winrate', style={'height': '300px'}, config={'displayModeBar': False}))
            ], className="shadow-sm border-secondary h-100"), width=6),
        ], className="mb-4"),

        # --- ROW 2: COSTS & STRIKES ---
        dbc.Row([
            dbc.Col(dbc.Card([
                dbc.CardHeader("PREMIUM SPENT PER WEEK (BURN RATE)", className="fw-bold font-monospace small"), 
                dbc.CardBody(dcc.Graph(id='stats-chart-burn', style={'height': '300px'}, config={'displayModeBar': False}))
            ], className="shadow-sm border-secondary h-100"), width=6),
            
            dbc.Col(dbc.Card([
                dbc.CardHeader("PROFITABILITY BY STRIKE", className="fw-bold font-monospace small"), 
                dbc.CardBody(dcc.Graph(id='stats-chart-strike', style={'height': '300px'}, config={'displayModeBar': False}))
            ], className="shadow-sm border-secondary h-100"), width=6),
        ], className="mb-4"),

        # --- ROW 3: EQUITY CURVE ---
        dbc.Row([
            dbc.Col(dbc.Card([
                dbc.CardHeader("PORTFOLIO EQUITY GROWTH", className="fw-bold font-monospace small"), 
                dbc.CardBody(dcc.Graph(id='stats-chart-equity', style={'height': '350px'}, config={'displayModeBar': False}))
            ], className="shadow-sm border-secondary"), width=12),
        ], className="mb-4"),

    ], fluid=True, className="px-4 py-3")

# ==============================================================================
# 2. CALLBACKS
# ==============================================================================
@callback(
    [Output('stats-kpi-row', 'children'),
     Output('stats-chart-split', 'figure'),
     Output('stats-chart-winrate', 'figure'),
     Output('stats-chart-burn', 'figure'),
     Output('stats-chart-strike', 'figure'),
     Output('stats-chart-equity', 'figure')],
    [Input('stats-source', 'value'),
     Input('stats-profile', 'value')]
)
def update_stats(source, profile):
    df = forensics.fetch_scorecard_data(source, profile)
    
    empty_fig = go.Figure().update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    if df.empty: return [], empty_fig, empty_fig, empty_fig, empty_fig, empty_fig

    # PRE-PROCESS
    df['entry_time'] = pd.to_datetime(df['entry_time'])
    if df['entry_time'].dt.tz is None: df['entry_time'] = df['entry_time'].dt.tz_localize(TZ_UTC)
    df['entry_time'] = df['entry_time'].dt.tz_convert(TZ_PST)
    
    # Extract Type (C/P) and Strike from Ticker
    # Logic preserved exactly as original
    def parse_ticker(t):
        try:
            parts = t.split()
            for p in parts:
                if 'C' in p and p[:-1].isdigit(): return 'CALL', int(p[:-1])
                if 'P' in p and p[:-1].isdigit(): return 'PUT', int(p[:-1])
                if p.endswith('C'): return 'CALL', float(p[:-1])
                if p.endswith('P'): return 'PUT', float(p[:-1])
            return 'UNK', 0
        except: return 'UNK', 0

    df['Type'] = df['ticker'].apply(lambda x: 'CALL' if 'C ' in x or x.endswith('C') or 'C' in x.split()[1] else ('PUT' if 'P ' in x or x.endswith('P') or 'P' in x.split()[1] else 'UNK'))
    df['Strike'] = df['ticker'].apply(lambda x: ''.join([c for c in x.split()[1] if c.isdigit() or c=='.']) if len(x.split())>1 else '0')

    # 1. KPIs (Institutional Styling)
    net_pnl = df['pnl'].sum()
    win_rate = len(df[df['pnl']>0]) / len(df) * 100
    pf = df[df['pnl']>0]['pnl'].sum() / abs(df[df['pnl']<0]['pnl'].sum()) if len(df[df['pnl']<0]) > 0 else 0
    
    card_style = {"backgroundColor": "#1e293b", "borderColor": "#334155", "color": "white"}
    
    kpis = [
        dbc.Col(dbc.Card([html.H6("NET PnL", className="text-muted small fw-bold"), html.H3(f"${net_pnl:,.2f}", className="text-success font-monospace" if net_pnl>=0 else "text-danger font-monospace")], body=True, style=card_style)),
        dbc.Col(dbc.Card([html.H6("WIN RATE", className="text-muted small fw-bold"), html.H3(f"{win_rate:.1f}%", className="text-info font-monospace")], body=True, style=card_style)),
        dbc.Col(dbc.Card([html.H6("PROFIT FACTOR", className="text-muted small fw-bold"), html.H3(f"{pf:.2f}", className="text-warning font-monospace")], body=True, style=card_style)),
        dbc.Col(dbc.Card([html.H6("TOTAL TRADES", className="text-muted small fw-bold"), html.H3(f"{len(df)}", className="text-white font-monospace")], body=True, style=card_style)),
    ]

    # 2. SPLIT CHART
    split_grp = df.groupby('Type')['pnl'].sum().reset_index()
    fig_split = px.bar(split_grp, x='Type', y='pnl', color='pnl', color_continuous_scale=['#ef4444', '#333', '#22c55e'])
    fig_split.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="monospace"), coloraxis_showscale=False)

    # 3. WIN RATE CHART
    wr_grp = df.groupby('Type').apply(lambda x: len(x[x['pnl']>0])/len(x)*100).reset_index(name='WinRate')
    fig_wr = px.bar(wr_grp, x='Type', y='WinRate', color='WinRate', range_y=[0, 100], color_continuous_scale='Bluered_r')
    fig_wr.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="monospace"), coloraxis_showscale=False)

    # 4. BURN RATE
    df['Week'] = df['entry_time'].dt.to_period('W').astype(str)
    df['Cost'] = df['entry_price'] * df['quantity'] * 100
    burn_grp = df.groupby('Week')['Cost'].sum().reset_index()
    fig_burn = px.bar(burn_grp, x='Week', y='Cost', color_discrete_sequence=['#f39c12'])
    fig_burn.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="monospace"))

    # 5. STRIKE PERFORMANCE
    strike_df = df[df['Strike'] != '0'].copy()
    if not strike_df.empty:
        fig_strike = px.scatter(strike_df, x='Strike', y='pnl', color='Type', color_discrete_map={'CALL': '#22c55e', 'PUT': '#ef4444'})
        fig_strike.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="monospace"))
    else:
        fig_strike = empty_fig

    # 6. EQUITY CURVE
    df = df.sort_values('entry_time')
    df['Equity'] = df['pnl'].cumsum()
    fig_eq = px.line(df, x='entry_time', y='Equity')
    fig_eq.add_hline(y=0, line_dash="dash", line_color="gray")
    fig_eq.update_traces(line_color='#00bc8c', fill='tozeroy', fillcolor='rgba(0, 188, 140, 0.1)')
    fig_eq.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="monospace"))

    return kpis, fig_split, fig_wr, fig_burn, fig_strike, fig_eq