import sys
import duckdb
import pandas as pd
import numpy as np
import time
from datetime import datetime, timedelta
from pathlib import Path
import pytz

# ==============================================================================
# 1. PATH CONSTITUTION
# ==============================================================================
ROOT_DIR = Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT_DIR))

from src.utils import config
from src.utils.logger import get_logger

log = get_logger("BacktestEngine")

# ==============================================================================
# 2. HELPER FUNCTIONS
# ==============================================================================
def calculate_detailed_fees(num_contracts, fee_model="RH_GOLD"):
    fees = config.RH_FEES
    reg_fee = num_contracts * fees['REGULATORY_BASE']
    contract_fee = num_contracts * fees['CONTRACT_GOLD'] if fee_model == "RH_GOLD" else 0.0
    return reg_fee + contract_fee, reg_fee, contract_fee

def fetch_manifest_data(start_date, end_date):
    if not config.DB_FILE.exists(): return pd.DataFrame()
    con = duckdb.connect(str(config.DB_FILE), read_only=True)
    try:
        query = f"SELECT * FROM {config.TBL_MANIFEST} WHERE date >= '{start_date}' AND date <= '{end_date}' ORDER BY entry_timestamp_utc ASC"
        return con.execute(query).df()
    except Exception as e:
        log.error(f"Manifest Error: {e}")
        return pd.DataFrame()
    finally: con.close()

def fetch_option_data(ticker, target_date):
    con = duckdb.connect(str(config.DB_FILE), read_only=True)
    try:
        # Fetch Intraday bars for the ticker
        query = f"""
            SELECT datetime_utc, open, close 
            FROM {config.TBL_OPTIONS} 
            WHERE ticker = '{ticker}' 
            AND datetime_utc::DATE = '{target_date}' 
            ORDER BY datetime_utc ASC
        """
        df = con.execute(query).df()
        if not df.empty:
            # Enforce UTC to match Signal Timestamps
            if df['datetime_utc'].dt.tz is None:
                df['datetime_utc'] = df['datetime_utc'].dt.tz_localize(pytz.utc)
            else:
                df['datetime_utc'] = df['datetime_utc'].dt.tz_convert(pytz.utc)
        return df
    except: return pd.DataFrame()
    finally: con.close()

# ==============================================================================
# 3. CORE ENGINE
# ==============================================================================
def run_backtest_session(initial_balance=1000, start_date=None, end_date=None, selection_mode='FIRST', strategy_mode='Fractal'):
    """
    Executes the backtest with specific Strategy Mode logic.
    """
    # 1. Date Defaults
    if not start_date: start_date = (datetime.now() - timedelta(days=30)).strftime('%Y-%m-%d')
    if not end_date: end_date = datetime.now().strftime('%Y-%m-%d')

    # 2. Load Signals
    manifest = fetch_manifest_data(start_date, end_date)
    if manifest.empty: return pd.DataFrame()

    trades = []
    balance = float(initial_balance)
    manifest['date_str'] = pd.to_datetime(manifest['date']).dt.strftime('%Y-%m-%d')
    grouped = manifest.groupby('date_str')

    log.info(f"🚀 Running Sim: {start_date} to {end_date} | Mode: {strategy_mode}")

    for date_str, daily_signals in grouped:
        daily_candidates = []
        
        for _, sig in daily_signals.iterrows():
            ts_ms = sig['entry_timestamp_utc']
            trade_type = sig['trade_type'].upper() # CALL or PUT
            
            # --- STRATEGY FILTERING LOGIC ---
            # 1. Pure Directional
            if strategy_mode == 'Call' and 'PUT' in trade_type: continue
            if strategy_mode == 'Put' and 'CALL' in trade_type: continue
            
            # 2. 75/25 Bias Logic
            # "Call 75/25" means we prioritize Calls. We only take Puts if no Calls exist (or strictly secondary).
            # For simplicity: If bias is Call, and this is a Put, we skip it IF we already have a candidate.
            if strategy_mode == 'Call 75/25' and 'PUT' in trade_type and len(daily_candidates) > 0: continue
            if strategy_mode == 'Put 75/25' and 'CALL' in trade_type and len(daily_candidates) > 0: continue
            
            # 3. Fractal / Hedged
            # These modes accept all valid signals generated by the scanner.
            
            # --- DATA FETCHING ---
            xsp_target = sig['xsp_price']
            strike = int(xsp_target)
            opt_type = 'C' if 'CALL' in trade_type else 'P'
            date_fmt = pd.to_datetime(date_str).strftime('%y%m%d')
            ticker = f"O:XSP{date_fmt}{opt_type}{strike * 1000:08d}"
            
            df_opt = fetch_option_data(ticker, date_str)
            if df_opt.empty: continue # Night Ops missed this one

            # --- SMART FILL (Time Alignment) ---
            entry_time_utc = datetime.fromtimestamp(ts_ms / 1000, tz=pytz.utc)
            fill_window = entry_time_utc + timedelta(minutes=15)
            
            # Find first bar after signal
            fill_candidates = df_opt[
                (df_opt['datetime_utc'] >= entry_time_utc) & 
                (df_opt['datetime_utc'] <= fill_window)
            ]
            
            if fill_candidates.empty: continue
            
            entry_row = fill_candidates.iloc[0]
            entry_price = entry_row['open']
            
            # --- EXIT LOGIC (60m Fixed) ---
            exit_target_time = entry_row['datetime_utc'] + timedelta(minutes=60)
            exit_candidates = df_opt[df_opt['datetime_utc'] >= exit_target_time]
            
            if exit_candidates.empty: exit_row = df_opt.iloc[-1] # EOD Sell
            else: exit_row = exit_candidates.iloc[0]
            
            exit_price = exit_row['open']
            
            # --- PnL CALC ---
            cost = entry_price * 100
            revenue = exit_price * 100
            fees, _, _ = calculate_detailed_fees(1)
            net_pnl = revenue - cost - fees
            
            daily_candidates.append({
                'entry_time': entry_row['datetime_utc'].strftime('%H:%M:%S'),
                'exit_time': exit_row['datetime_utc'].strftime('%H:%M:%S'),
                'entry_timestamp': entry_row['datetime_utc'].timestamp(),
                'type': trade_type,
                'ticker': ticker,
                'entry': entry_price,
                'exit': exit_price,
                'contracts': 1,
                'pnl': net_pnl,
                'return': (net_pnl / cost) * 100,
                'balance_impact': net_pnl
            })

        # --- SELECTION ---
        if not daily_candidates: continue
        
        # Sort chronologically
        daily_candidates.sort(key=lambda x: x['entry_timestamp'])

        selected_trades = []
        if selection_mode == 'FIRST': selected_trades = [daily_candidates[0]]
        elif selection_mode == 'ALL': selected_trades = daily_candidates
        elif selection_mode == 'BEST':
            # Hindsight optimization
            daily_candidates.sort(key=lambda x: x['pnl'], reverse=True)
            selected_trades = [daily_candidates[0]]
            
        # --- COMMIT ---
        for t in selected_trades:
            balance += t['balance_impact']
            trades.append({
                'Date': date_str,
                'Time': t['entry_time'],
                'Exit_Time': t['exit_time'], # Explicit for Stats
                'Type': t['type'],
                'Ticker': t['ticker'],
                'Entry': f"${t['entry']:.2f}",
                'Exit': f"${t['exit']:.2f}",
                'Contracts': t['contracts'],
                'PnL': f"${t['pnl']:.2f}",
                'Return': f"{t['return']:.1f}%",
                'Balance': f"${balance:.2f}",
                'PnL_Raw': t['pnl']
            })

    return pd.DataFrame(trades)