import sys
import duckdb
import pandas as pd
import pytz
from datetime import datetime, time
from pathlib import Path

# ==============================================================================
# 1. SETUP
# ==============================================================================
ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.append(str(ROOT_DIR))

from src.utils import config
from src.utils.logger import get_logger
import src.core.strat_fractal as strategy

log = get_logger("SignalRegen")

# ⚡ SYSTEM VERIFIED TABLE NAME
TBL_MANIFEST = "trade_manifest"
START_DATE = "2025-12-01"

def robust_rth_filter(df):
    if df.empty: return df
    if df['datetime_utc'].dt.tz is None:
        first_hour = df.iloc[0]['datetime_utc'].hour
        if first_hour == 9: 
            df['dt_ny'] = df['datetime_utc'].dt.tz_localize('America/New_York')
        else:
            df['dt_ny'] = df['datetime_utc'].dt.tz_localize('UTC').dt.tz_convert('America/New_York')
    else:
        df['dt_ny'] = df['datetime_utc'].dt.tz_convert('America/New_York')
        
    market_open, market_close = time(9, 30), time(16, 0)
    mask = (df['dt_ny'].dt.time >= market_open) & (df['dt_ny'].dt.time < market_close)
    return df[mask].copy()

def run_regeneration():
    if not config.DB_FILE.exists():
        log.error("Vault not found.")
        return

    log.info(f"🧠 REGENERATING SIGNALS FOR {TBL_MANIFEST} FROM: {START_DATE}")
    con = duckdb.connect(str(config.DB_FILE))
    
    try:
        log.info("   Fetching Index History...")
        vix_df = con.execute(f"SELECT datetime_utc, close FROM indices_1m WHERE ticker='VIX' AND datetime_utc >= '{START_DATE}' ORDER BY datetime_utc").df()
        xsp_df = con.execute(f"SELECT datetime_utc, close FROM indices_1m WHERE ticker='XSP' AND datetime_utc >= '{START_DATE}' ORDER BY datetime_utc").df()
    except Exception as e:
        log.error(f"   ❌ Extraction Failed: {e}")
        con.close()
        return

    if len(vix_df) < 100:
        log.warning("   ⚠️ Insufficient data found.")
        con.close()
        return

    log.info(f"   Applying Fractal Logic to {len(xsp_df)} candles...")
    vix_df['datetime_utc'] = pd.to_datetime(vix_df['datetime_utc'])
    xsp_df['datetime_utc'] = pd.to_datetime(xsp_df['datetime_utc'])
    
    all_signals = strategy.apply_fractal_logic(vix_df, xsp_df)
    
    if not all_signals.empty:
        all_signals = robust_rth_filter(all_signals)
        log.info(f"   🔎 Signals Found: {len(all_signals)}")
    else:
        log.warning("   ⚠️ No signals generated by Strategy Logic.")
        con.close()
        return

    # --- VAULT UPDATE ---
    log.info(f"   📝 Cleaning and Updating {TBL_MANIFEST}...")
    con.execute(f"DELETE FROM {TBL_MANIFEST} WHERE date >= '{START_DATE}'")
    
    count = 0
    for i, row in all_signals.iterrows():
        ts_bigint = int(pd.to_datetime(row['datetime_utc']).timestamp() * 1000)
        sig_name = "BULL_FRACTAL" if row['signal'] == 1 else "BEAR_FRACTAL"
        trade_type = 'CALL' if row['signal'] == 1 else 'PUT'
        
        con.execute(f"INSERT INTO {TBL_MANIFEST} VALUES (?, ?, ?, ?, ?, ?, ?)", 
                    [ts_bigint, row['datetime_utc'].date(), sig_name, float(row['close']), 
                     trade_type, 'Fractal Crossover (Regen)', 1.0])
        count += 1

    con.close()
    log.info(f"✅ REGENERATION COMPLETE. {count} signals now live in Vault.")

if __name__ == "__main__":
    run_regeneration()