import sys
import os
import duckdb
from pathlib import Path

# ==============================================================================
# 1. ARCHITECTURE V2.6: PATH CONSTITUTION
# ==============================================================================
# File: src/data/db_schema.py
# Root: ../../
ROOT_DIR = Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT_DIR))

from src.utils import config
from src.utils.logger import get_logger

log = get_logger("SchemaManager")

def initialize_database():
    log.info(f"🔌 Connecting to Vault: {config.DB_FILE}")
    con = duckdb.connect(str(config.DB_FILE))
    
    # ------------------------------------------------------------------
    # 1. MARKET INDICES (The Truth)
    # SPX, VIX, IRX (Rates)
    # ------------------------------------------------------------------
    log.info(f"🔨 Initializing: {config.TBL_INDICES}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_INDICES}")
    con.execute(f"""
    CREATE TABLE {config.TBL_INDICES} (
        datetime_utc TIMESTAMP NOT NULL,
        ticker VARCHAR NOT NULL,
        open DOUBLE, high DOUBLE, low DOUBLE, close DOUBLE, volume DOUBLE,
        PRIMARY KEY (datetime_utc, ticker)
    )""")
    
    # Risk Free Rate (Daily)
    log.info(f"🔨 Initializing: {config.TBL_IRX}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_IRX}")
    con.execute(f"""
    CREATE TABLE {config.TBL_IRX} (
        date DATE,
        ticker VARCHAR,
        rate DOUBLE,
        PRIMARY KEY (date)
    )""")

    # Futures Archive (Sentinel Layer)
    log.info(f"🔨 Initializing: {config.TBL_FUTURES}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_FUTURES}")
    con.execute(f"""
    CREATE TABLE {config.TBL_FUTURES} (
        datetime_utc TIMESTAMP NOT NULL,
        ticker VARCHAR NOT NULL,
        open DOUBLE, high DOUBLE, low DOUBLE, close DOUBLE, volume DOUBLE,
        PRIMARY KEY (datetime_utc, ticker)
    )""")

    # ------------------------------------------------------------------
    # 2. OPTION VEHICLE (The Product)
    # ------------------------------------------------------------------
    log.info(f"🔨 Initializing: {config.TBL_OPTIONS}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_OPTIONS}")
    con.execute(f"""
    CREATE TABLE {config.TBL_OPTIONS} (
        datetime_utc TIMESTAMP,
        ticker VARCHAR,
        expiration DATE,
        strike DOUBLE,
        type VARCHAR, -- 'C' or 'P'
        open DOUBLE, high DOUBLE, low DOUBLE, close DOUBLE, volume DOUBLE,
        iv DOUBLE, delta DOUBLE, gamma DOUBLE, vega DOUBLE, theta DOUBLE,
        underlying_price DOUBLE,
        risk_free_rate DOUBLE,
        PRIMARY KEY (datetime_utc, ticker) -- <--- CRITICAL FIX: ENABLE UPSERT
    )""")

    # ------------------------------------------------------------------
    # 3. STRATEGY DATA (Core Engine)
    # ------------------------------------------------------------------
    
    # Strategy Manifest (Generated by Scanner)
    # UPDATED: Added allocation_pct for Straddle-Bias Protocol
    log.info(f"🔨 Initializing: {config.TBL_MANIFEST}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_MANIFEST}")
    con.execute(f"""
    CREATE TABLE {config.TBL_MANIFEST} (
        entry_timestamp_utc BIGINT NOT NULL, -- PK for lookups
        date DATE,
        signal_type VARCHAR, -- e.g., 'VIX_FRACTAL_LONG'
        xsp_price DOUBLE,    -- Est. Spot Price at Signal
        trade_type VARCHAR,  -- 'call', 'put', 'straddle'
        meta_data VARCHAR,   -- Stored JSON or Text reasoning
        allocation_pct DOUBLE, -- NEW: Used for Straddle-Bias Sizing (75/25)
        PRIMARY KEY (entry_timestamp_utc)
    )""")
    
    # Macro Flow State (Generated by Macro Flow Engine)
    # Stores the rolling 20-day Bull/Bear bias
    log.info(f"🔨 Initializing: {config.TBL_MACRO_FLOW}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_MACRO_FLOW}")
    con.execute(f"""
    CREATE TABLE {config.TBL_MACRO_FLOW} (
        date DATE NOT NULL,
        flow_bias VARCHAR,     -- 'BULL', 'BEAR', or 'NEUTRAL'
        bull_pct DOUBLE,       -- Bull Day percentage over lookback
        bear_pct DOUBLE,       -- Bear Day percentage over lookback
        PRIMARY KEY (date)
    )""")
    
    # Simulation Log (Generated by Backtester)
    log.info(f"🔨 Initializing: {config.TBL_SIM_LOG}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_SIM_LOG}")
    con.execute(f"""
    CREATE TABLE {config.TBL_SIM_LOG} (
        entry_time TIMESTAMP, 
        ticker VARCHAR, 
        net_pnl DOUBLE, 
        return_pct DOUBLE, 
        reason VARCHAR, 
        entry_price DOUBLE, 
        exit_price DOUBLE
    )""")
    
    # ------------------------------------------------------------------
    # 4. VERIFICATION
    # ------------------------------------------------------------------
    tables = con.execute("SHOW TABLES").fetchall()
    table_names = [t[0] for t in tables]
    log.info(f"✅ Database Initialized. Tables: {table_names}")
    con.close()

if __name__ == "__main__":
    print("\n⚠️  CRITICAL WARNING ⚠️")
    print("This script will DELETE ALL DATA in the Vault and recreate the schema.")
    print(f"Target DB: {config.DB_FILE}")
    confirm = input("Type 'CONFIRM' to proceed: ")
    
    if confirm == "CONFIRM":
        initialize_database()
    else:
        print("❌ Aborted.")