import sys
import os
import duckdb
from pathlib import Path

# ==============================================================================
# 1. ARCHITECTURE V2.5: PATH CONSTITUTION
# ==============================================================================
# File: src/data/db_schema.py
# Root: ../../
ROOT_DIR = Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT_DIR))

from src.utils import config
from src.utils.logger import get_logger

log = get_logger("SchemaManager")

def initialize_database():
    log.info(f"🔌 Connecting to Vault: {config.DB_FILE}")
    con = duckdb.connect(str(config.DB_FILE))
    
    # ------------------------------------------------------------------
    # 1. MARKET INDICES (The Truth)
    # SPX, VIX, IRX (Rates)
    # ------------------------------------------------------------------
    log.info(f"🔨 Initializing: {config.TBL_INDICES}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_INDICES}")
    con.execute(f"""
    CREATE TABLE {config.TBL_INDICES} (
        datetime_utc TIMESTAMP NOT NULL,
        ticker VARCHAR NOT NULL,
        open DOUBLE, high DOUBLE, low DOUBLE, close DOUBLE, volume DOUBLE,
        PRIMARY KEY (datetime_utc, ticker)
    )""")
    
    # Risk Free Rate (Daily)
    log.info(f"🔨 Initializing: {config.TBL_IRX}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_IRX}")
    con.execute(f"""
    CREATE TABLE {config.TBL_IRX} (
        date DATE NOT NULL PRIMARY KEY,
        rate DOUBLE
    )""")

    # ------------------------------------------------------------------
    # 2. DERIVATIVES (Options & Futures)
    # ------------------------------------------------------------------
    # XSP Options (1-Minute Aggregates + Greeks)
    log.info(f"🔨 Initializing: {config.TBL_OPTIONS}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_OPTIONS}")
    con.execute(f"""
    CREATE TABLE {config.TBL_OPTIONS} (
        datetime_utc TIMESTAMP NOT NULL,
        ticker VARCHAR NOT NULL,
        
        -- Contract Specs (Parsed or Nullable initially)
        expiration DATE, 
        strike DOUBLE, 
        type VARCHAR,
        
        -- OHLCV
        open DOUBLE, high DOUBLE, low DOUBLE, close DOUBLE, volume DOUBLE,
        
        -- Calculated Greeks (Engine v2.5)
        iv DOUBLE, 
        delta DOUBLE, 
        gamma DOUBLE, 
        vega DOUBLE, 
        theta DOUBLE,
        
        PRIMARY KEY (datetime_utc, ticker)
    )""")

    # Futures (ES) - Optional/Proxy Use
    log.info(f"🔨 Initializing: {config.TBL_FUTURES}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_FUTURES}")
    con.execute(f"""
    CREATE TABLE {config.TBL_FUTURES} (
        datetime_utc TIMESTAMP NOT NULL,
        ticker VARCHAR NOT NULL,
        open DOUBLE, high DOUBLE, low DOUBLE, close DOUBLE, volume DOUBLE,
        PRIMARY KEY (datetime_utc, ticker)
    )""")

    # ------------------------------------------------------------------
    # 3. STRATEGY ENGINE (Manifests & Logs)
    # ------------------------------------------------------------------
    # Trade Manifest (Generated by Scanner)
    log.info(f"🔨 Initializing: {config.TBL_MANIFEST}")
    con.execute(f"DROP TABLE IF EXISTS {config.TBL_MANIFEST}")
    con.execute(f"""
    CREATE TABLE {config.TBL_MANIFEST} (
        entry_timestamp_utc BIGINT NOT NULL, -- PK for lookups
        date DATE,
        signal_type VARCHAR, -- e.g., 'VIX_FRACTAL_LONG'
        xsp_price DOUBLE,    -- Est. Spot Price at Signal
        trade_type VARCHAR,  -- 'call', 'put', 'straddle'
        meta_data VARCHAR,   -- Stored JSON or Text reasoning
        PRIMARY KEY (entry_timestamp_utc)
    )""")
    
    # Simulation Log (Generated by Backtester)
    log.info("🔨 Initializing: active_simulation_log")
    con.execute("DROP TABLE IF EXISTS active_simulation_log")
    con.execute("""
    CREATE TABLE active_simulation_log (
        entry_time TIMESTAMP, 
        ticker VARCHAR, 
        net_pnl DOUBLE, 
        return_pct DOUBLE, 
        reason VARCHAR, 
        entry_price DOUBLE, 
        exit_price DOUBLE
    )""")
    
    # ------------------------------------------------------------------
    # 4. VERIFICATION
    # ------------------------------------------------------------------
    tables = con.execute("SHOW TABLES").fetchall()
    table_names = [t[0] for t in tables]
    log.info(f"✅ Database Initialized. Tables: {table_names}")
    con.close()

if __name__ == "__main__":
    print("\n⚠️  CRITICAL WARNING ⚠️")
    print("This script will DELETE ALL DATA in the Vault and recreate the schema.")
    print(f"Target: {config.DB_FILE}")
    confirm = input("Type 'DELETE' to confirm: ")
    
    if confirm == 'DELETE':
        initialize_database()
    else:
        print("❌ Operation Aborted.")